//
//  WTConstant.h
//  omim
//
//  Created by coca on 2013/01/07.
//  Copyright (c) 2013年 WowTech Inc. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "WTNetworkTaskConstant.h"
#import "WTChatMessageConstant.h"
@interface WTConstant : NSObject


// DOCUMENT CONSTANT
FOUNDATION_EXPORT NSString* const WT_MULTI_MEDIA_FOLDER_NAME;      /*< a folder contains all the media files*/
FOUNDATION_EXPORT NSString* const WT_USERINFO_FOLDER_NAME;          /*< a folder contains user's profile*/
FOUNDATION_EXPORT NSString* const WT_BUDDYINFO_FOLDER_NAME;         /*< a folder contains buddies' info*/


//reserved keys in NSDefault
FOUNDATION_EXPORT NSString* const WT_APPLY_TIMES;
FOUNDATION_EXPORT NSString* const WT_DEMO_MODE_CODE;

FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_TIME_OFFSET;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_UID;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_USERNAME;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_NICKNAME;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_STATUS;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_BIRTHDAY;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_GENDER;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_AREA;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_SERVER_VERSION;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_CLIENT_VERSION;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_AUTO_ADD_BUDDY;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_ADDABLE;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_ACCEPT_STRANGER_CALL;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_SHOW_PUSH_DETAIL;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_TOKEN_UPLOADED;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_ACTIVE_APP_TYPE;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_DOMAIN;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_DEMO_MODE_CODE;
FOUNDATION_EXPORT NSString *const WT_USERDEFAULT_COUNTRY_CODE;


FOUNDATION_EXPORT NSString *const WT_NOTIFICATION_AUTH_FAILED;
FOUNDATION_EXPORT NSString *const WT_NOTIFICATION_MOMENT_LIST_CHANGED;
@end
