//
//  WTNetworkTaskConstant.h
//  omimIOSAPI
//
//  Created by coca on 2012/12/13.
//  Copyright (c) 2012年 coca. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface WTNetworkTaskConstant : NSObject
#pragma mark -  Network Type 
FOUNDATION_EXPORT NSString* const WT_UPLOAD_MEDIAFILE;
FOUNDATION_EXPORT NSString* const WT_UPLOAD_MSGFILE;
FOUNDATION_EXPORT NSString* const WT_DOWNLOAD_MSGFILE;
FOUNDATION_EXPORT NSString* const WT_GET_ACCOUNTS_UNREAD_COUNT;
FOUNDATION_EXPORT NSString* const WT_UPLOAD_MEDIAMESSAGE_ORIGINAL;
FOUNDATION_EXPORT NSString* const WT_UPLOAD_MEDIAMESSAGE_THUMBNAIL;
FOUNDATION_EXPORT NSString* const WT_DOWNLOAD_MEDIAMESSAGE_ORIGINAL;
FOUNDATION_EXPORT NSString* const WT_DOWNLOAD_MEDIAMESSAGE_THUMBNAIL;

FOUNDATION_EXPORT NSString* const WT_REPORT_UNREAD_MESSAGES;
FOUNDATION_EXPORT NSString* const WT_REPORT_PUSH_TOKEN_TO_SERVER;
FOUNDATION_EXPORT NSString* const WT_REPORT_EMPTY_TOKEN_TO_SERVER;

FOUNDATION_EXPORT NSString* const WT_REQUIRE_ACCESS_CODE;
FOUNDATION_EXPORT NSString* const WT_REQUIRE_IVR_ACCESS_CODE;
FOUNDATION_EXPORT NSString* const WT_VALIDATE_ACCESS_CODE;

FOUNDATION_EXPORT NSString* const WT_GET_LATEST_VERSION_INFO;

FOUNDATION_EXPORT NSString* const WT_GET_MY_PROFILE;
FOUNDATION_EXPORT NSString* const WT_UPDATE_PROFILE;

FOUNDATION_EXPORT NSString* const WT_UPLOAD_CONTACT_BOOK;
FOUNDATION_EXPORT NSString* const WT_INCREASE_CONTACT_BOOK_IN_SERVER;
FOUNDATION_EXPORT NSString* const WT_DECREASE_CONTACT_BOOK_IN_SERVER;

FOUNDATION_EXPORT NSString* const WT_GET_A_BUDDY;
FOUNDATION_EXPORT NSString* const WT_GET_BUDDY_LIST;
FOUNDATION_EXPORT NSString* const WT_GET_MATCHED_BUDDYS;
FOUNDATION_EXPORT NSString* const WT_GET_POSSIBLE_BUDDYS;
FOUNDATION_EXPORT NSString* const WT_GET_BLOCKED_BUDDYS;
FOUNDATION_EXPORT NSString* const WT_SCAN_NUMBER_FOR_BUDDY;

FOUNDATION_EXPORT NSString* const WT_UPDATE_MY_PHOTO_ORIGINAL;
FOUNDATION_EXPORT NSString* const WT_UPDATE_MT_PHOTO_THUMBNAIL;

FOUNDATION_EXPORT NSString* const WT_GET_PRIVACY_SETTING;
FOUNDATION_EXPORT NSString* const WT_SET_PRIVACY;

FOUNDATION_EXPORT NSString* const WT_DEACTIVE_ACCOUNT;

FOUNDATION_EXPORT NSString* const WT_ADJUST_UTC_TIME_WITH_SERVER;

FOUNDATION_EXPORT NSString* const WT_ADD_BUDDY;
FOUNDATION_EXPORT NSString* const WT_BLOCK_BUDDY;
FOUNDATION_EXPORT NSString* const WT_UNBLOCK_BUDDY;

FOUNDATION_EXPORT NSString* const WT_GET_BUDDY_PHOTO_ORIGINAL;
FOUNDATION_EXPORT NSString* const WT_GET_BUDDY_PHOTO_THUMBNAIL;

FOUNDATION_EXPORT NSString* const WT_GET_FILE_FROM_SERVER;

FOUNDATION_EXPORT NSString* const WT_CREATE_CHAT_GROUP;
FOUNDATION_EXPORT NSString* const WT_JOIN_CHAT_GROUP;
FOUNDATION_EXPORT NSString* const WT_LEAVE_CHAT_GROUP;
FOUNDATION_EXPORT NSString* const WT_GET_GROUP_MEMBERS;
FOUNDATION_EXPORT NSString* const WT_ADD_GROUP_MEMBERS;
FOUNDATION_EXPORT NSString* const WT_GET_GROUP_INFO;

FOUNDATION_EXPORT NSString* const WT_SEND_GROUP_MESSAGES;

FOUNDATION_EXPORT NSString* const WT_GET_UNSUPPORTED_DEVICE;

FOUNDATION_EXPORT NSString* const WT_GET_STAMP_FILE_FROM_SERVER;
FOUNDATION_EXPORT NSString* const WT_EMAIL_ADDRESS;
FOUNDATION_EXPORT NSString* const WT_SET_ACTIVE_APP_TYPE;
FOUNDATION_EXPORT NSString* const WT_GET_ACTIVE_APP_TYPE;

FOUNDATION_EXPORT NSString* const WT_AUTO_REGISTER;
FOUNDATION_EXPORT NSString* const WT_REGISTER_WITH_MAIL;
FOUNDATION_EXPORT NSString* const WT_REGISTER_WITH_USERID;
FOUNDATION_EXPORT NSString* const WT_LOGIN_WITH_USER;

FOUNDATION_EXPORT NSString* const WT_GET_EVENT_INFO;
FOUNDATION_EXPORT NSString* const WT_GET_JOINABLE_EVENTS;
FOUNDATION_EXPORT NSString* const WT_BIND_EMAIL_STATUS;
FOUNDATION_EXPORT NSString* const WT_VERIYF_EMAIL;
FOUNDATION_EXPORT NSString* const WT_UNBIND_EMAIL;
FOUNDATION_EXPORT NSString* const WT_RETRIVE_PASS;
FOUNDATION_EXPORT NSString* const WT_SEND_CODEFOR_RETRPASS;
FOUNDATION_EXPORT NSString* const WT_CHECK_CODEFOR_RETPASS;
FOUNDATION_EXPORT NSString* const WT_LOGOUT;
FOUNDATION_EXPORT NSString* const WT_CHANGE_WOWTALK_ID;
FOUNDATION_EXPORT NSString* const WT_CHANGE_PASSWORD;
FOUNDATION_EXPORT NSString* const WT_GET_USER_BY_UID;
FOUNDATION_EXPORT NSString* const WT_GET_USER_BY_WOWTALKID;


FOUNDATION_EXPORT NSString* const WT_JOIN_EVENT;
FOUNDATION_EXPORT NSString* const WT_JOIN_EVENT_WITH_DETAIL;
FOUNDATION_EXPORT NSString* const WT_GET_PREVIOUS_EVENTS;
FOUNDATION_EXPORT NSString* const WT_GET_LATEST_EVENTS;
FOUNDATION_EXPORT NSString* const WT_CANCEL_THE_EVENT;
FOUNDATION_EXPORT NSString* const WT_GET_JOINED_EVENTS;
FOUNDATION_EXPORT NSString* const WT_LIKE_THE_EVENT;
FOUNDATION_EXPORT NSString* const WT_UNLIKE_THE_EVENT;
FOUNDATION_EXPORT NSString* const WT_SEARCH_EVENT_BY_CATEGORY;
FOUNDATION_EXPORT NSString* const WT_SEARCH_EVENT_BY_TAG;
FOUNDATION_EXPORT NSString* const WT_SEARCH_EVENT_BY_LOCATION;
FOUNDATION_EXPORT NSString* const WT_UPLOAD_EVENT_MEDIA_ORIGINAL;
FOUNDATION_EXPORT NSString* const WT_UPLOAD_EVENT_MEDIA_THUMBNAIL;
FOUNDATION_EXPORT NSString* const WT_DOWNLOAD_EVENT_MEDIA;



FOUNDATION_EXPORT NSString* const WT_BIND_EMAIL;
FOUNDATION_EXPORT NSString* const WT_BIND_PHONE_NUMBER;
FOUNDATION_EXPORT NSString* const WT_VERIFY_EMAIL;
FOUNDATION_EXPORT NSString* const WT_VERIFY_PHONE_NUMBER;
FOUNDATION_EXPORT NSString* const WT_UNLINK_EMAIL;
FOUNDATION_EXPORT NSString* const WT_UNLINK_PHONE_NUMBER;
FOUNDATION_EXPORT NSString* const WT_SEARCH_BUDDY;

FOUNDATION_EXPORT NSString* const WT_SEND_ACCESS_CODE;
FOUNDATION_EXPORT NSString* const WT_RESET_PASSWORD;

FOUNDATION_EXPORT NSString* const WT_ADD_MOMENT;
FOUNDATION_EXPORT NSString* const WT_ADD_MOMENT_SURVEY;
FOUNDATION_EXPORT NSString* const WT_VOTE_MOMENT_SURVEY;
FOUNDATION_EXPORT NSString* const WT_UPLOAD_MOMENT_MULTIMEDIA;
FOUNDATION_EXPORT NSString* const WT_DELETE_MOMENT;
FOUNDATION_EXPORT NSString* const WT_REVIEW_MOMENT;
FOUNDATION_EXPORT NSString* const WT_REPLY_TO_REVIEW;
FOUNDATION_EXPORT NSString* const WT_DELETE_MOMENT_REVIEW;
FOUNDATION_EXPORT NSString* const WT_GET_MOMENTS_FOR_ALL_BUDDIES;
FOUNDATION_EXPORT NSString* const WT_GET_LATEST_MOMENT_FOR_BUDDY;
FOUNDATION_EXPORT NSString* const WT_GET_REVIEW_FOR_MOMENT;
FOUNDATION_EXPORT NSString* const WT_GET_PREVIOUS_REVIEW_FOR_MOMENT;
FOUNDATION_EXPORT NSString* const WT_GET_LATEST_REVIEWS_FOR_ME;
FOUNDATION_EXPORT NSString* const WT_SET_REVIEW_STATUS_READ;
FOUNDATION_EXPORT NSString* const WT_DOWNLOAD_MOMENT_MULTIMEDIA;
FOUNDATION_EXPORT NSString* const WT_UPLOAD_MOMENT_MEDIA_ORIGINAL;
FOUNDATION_EXPORT NSString* const WT_UPLOAD_MOMENT_MEDIA_THUMBNAIL;
FOUNDATION_EXPORT NSString* const WT_SET_ALBUM_COVER;
FOUNDATION_EXPORT NSString* const WT_GET_ALBUM_COVER;
FOUNDATION_EXPORT NSString* const WT_REMOVE_ALBUM_COVER;
FOUNDATION_EXPORT NSString* const WT_UPLOAD_ALBUM_COVER;
FOUNDATION_EXPORT NSString* const WT_DOWNLOAD_ALBUM_COVER;

FOUNDATION_EXPORT NSString* const WT_GET_MOMENTS_FOR_GROUP;

FOUNDATION_EXPORT NSString* const WT_USER_BECOME_ACTIVE;

FOUNDATION_EXPORT NSString* const WT_SEND_MSG_TO_OFFICIAL_USER;

FOUNDATION_EXPORT NSString* const WT_GET_FRIEND_REQUEST;

FOUNDATION_EXPORT NSString* const WT_REJECT_FRIEND_REQUEST;
FOUNDATION_EXPORT NSString* const WT_REMOVE_BUDDY;
FOUNDATION_EXPORT NSString* const WT_KICKOUT_GROUP;

FOUNDATION_EXPORT NSString* const WT_ACTIVATE_NUMBER_AS_BUDDY;

FOUNDATION_EXPORT NSString* const WT_GET_NEARBY_BUDDYS;
FOUNDATION_EXPORT NSString* const WT_GET_NEARBY_GROUPS;


FOUNDATION_EXPORT NSString* const WT_GET_VERSION;



FOUNDATION_EXPORT NSString* const WT_SEND_ENMERGENCY_MESSAGE;

FOUNDATION_EXPORT NSString* const WT_GET_SCHOOL_MEMBERS;


//fixed group
FOUNDATION_EXPORT NSString* const WT_UPLOAD_GROUP_AVATAR;
FOUNDATION_EXPORT NSString* const WT_UPLOAD_GROUP_AVATAR_THUMBNAIL;
FOUNDATION_EXPORT NSString* const WT_GET_GROUP_AVATAR;
FOUNDATION_EXPORT NSString* const WT_GET_GROUP_AVATAR_THUMBNAIL;
FOUNDATION_EXPORT NSString* const WT_CREATE_FIXED_GROUP;
FOUNDATION_EXPORT NSString* const WT_EDIT_GROUP_INFO;
FOUNDATION_EXPORT NSString* const WT_UPDATE_GROUP_AVATAR_TIMESTAMP;
FOUNDATION_EXPORT NSString* const WT_DISMISS_GROUP;
FOUNDATION_EXPORT NSString* const WT_REQUEST_TO_JOIN_GROUP;
FOUNDATION_EXPORT NSString* const WT_GET_GROUP_PENDING_MEMBERS;
FOUNDATION_EXPORT NSString* const WT_REMOVE_GROUP_MEMBERS;
FOUNDATION_EXPORT NSString* const WT_GET_GROUP_BY_GROUPID;
FOUNDATION_EXPORT NSString* const WT_SET_USER_LEVEL;
FOUNDATION_EXPORT NSString* const WT_GET_MY_GROUPS;
FOUNDATION_EXPORT NSString* const WT_REJECT_GROUP_APPLICATION;
FOUNDATION_EXPORT NSString* const WT_SEARCH_GROUP_BY_KEY;
FOUNDATION_EXPORT NSString* const WT_GET_ALL_JOIN_GROUP_REQUEST;
FOUNDATION_EXPORT NSString* const WT_GET_ALL_PENDING_REQUEST;

FOUNDATION_EXPORT NSString* const WT_GET_ALL_GROUPS_IN_COMPANY;

#pragma mark - Favorite related
FOUNDATION_EXPORT NSString* const WT_FAVORITE_A_GROUP;
FOUNDATION_EXPORT NSString* const WT_FAVORITE_GROUPS;
FOUNDATION_EXPORT NSString* const WT_FAVORITE_A_BUDDY;
FOUNDATION_EXPORT NSString* const WT_FAVORITE_BUDDIES;
FOUNDATION_EXPORT NSString* const WT_GET_FAVORITE_ITEMS;

FOUNDATION_EXPORT NSString* const WT_DEFAVORITE_BUDDY;
FOUNDATION_EXPORT NSString* const WT_DEFAVORITE_GROUP;

FOUNDATION_EXPORT NSString* const WT_GET_LATEST_CONTACT_LIST;
#pragma mark - biz group
FOUNDATION_EXPORT NSString* const WT_GET_COMPANY_STRUCTURE;
FOUNDATION_EXPORT NSString* const WT_GET_COMPANY_STRUCTURE_UPDATES;
FOUNDATION_EXPORT NSString* const WT_GET_GROUPS_IN_CORP;
FOUNDATION_EXPORT NSString* const WT_GET_MEMBERS_IN_DEPARTMENT;

#pragma mark -
#pragma mark -- Reserved Task Info Keys

FOUNDATION_EXPORT NSString* const WT_MESSAGE;
FOUNDATION_EXPORT NSString* const WT_FILE_PATH_LOCAL;
FOUNDATION_EXPORT NSString* const WT_BUDDY_ID;


#pragma mark -
#pragma mark Reserved Keys In userinfo contained in the posted notif.  Note WT_MESSAGE is also posted when a task is uploading or downloading a message.

FOUNDATION_EXPORT NSString* const WT_ERROR;
FOUNDATION_EXPORT NSInteger const WT_ERROR_AUTH_ERROR;
FOUNDATION_EXPORT NSString* const WT_PASSED_IN_NOTIFDATA;
FOUNDATION_EXPORT NSString* const WT_DID_SEND_THE_MESSAGE;
FOUNDATION_EXPORT NSString* const WT_DID_UPLOAD_THE_THUMBNAIL;
FOUNDATION_EXPORT NSString* const WT_DID_UPLOAD_THE_ORIGINAL_FILE;
FOUNDATION_EXPORT NSString* const WT_IS_SENDING_GROUP_MESSAGE;
FOUNDATION_EXPORT NSString* const WT_DID_DOWNLOAD_THE_THUMBNAIL;
FOUNDATION_EXPORT NSString* const WT_DID_DOWNLOAD_THE_ORIGINAL_FILE;
FOUNDATION_EXPORT NSString* const WT_DID_DOWNLOAD_THE_MSG_RECORD_FILE;

FOUNDATION_EXPORT NSString* const WT_GROUP_ID;
FOUNDATION_EXPORT NSString* const WT_SHORT_GROUP_ID;
FOUNDATION_EXPORT NSString* const WT_BUDDY;
FOUNDATION_EXPORT NSString* const WT_SEARCH_RESULT;
FOUNDATION_EXPORT NSString* const WT_PENDING_REQUEST;

FOUNDATION_EXPORT NSString* const WT_GET_CHAT_HISTORY;
FOUNDATION_EXPORT NSString* const WT_GET_CHAT_HISTORY_COUNT;
FOUNDATION_EXPORT NSString* const WT_GET_OFFLINE_MESSAGE;

FOUNDATION_EXPORT NSString* const WT_NEED_RELOAD_TIMELINE_MOMENT_TABLE;
FOUNDATION_EXPORT NSString* const TIMELINE_VIEW_NEW_REVIEWS;
FOUNDATION_EXPORT NSString* const TIMELINE_COVER_IMAGE_CHANGED;
FOUNDATION_EXPORT NSString* const SETTING_ATTACH_USER_STATE_CHANGE;
FOUNDATION_EXPORT NSString* const TIMELINE_MOMENT_STATUS_CHANGED;
FOUNDATION_EXPORT NSString* const BIZ_MEMBER_DELETED;
FOUNDATION_EXPORT NSString* const BIZ_MEMBER_UPDATED;

FOUNDATION_EXPORT NSString* const MOMENT_ACTION_NEW_MOMENT;
FOUNDATION_EXPORT NSString* const MOMENT_ACTION_REFRESH_MOMENT;
FOUNDATION_EXPORT NSString* const MOMENT_ACTION_DELETE_MOMENT;

FOUNDATION_EXPORT NSString* const BIZ_MEMBER_INFO_DID_UPDATE;

FOUNDATION_EXPORT NSString* const WT_GET_SINGLE_MOMENT;
FOUNDATION_EXPORT NSString* const WT_BIND_INVITATION_CODE;
FOUNDATION_EXPORT NSString* const WT_LOGIN_WITH_INVITATION_CODE;
FOUNDATION_EXPORT NSString* const WT_GET_SCHOOL_STRUCTURE;


// MyClassNetWork
#pragma MARK - MyClassNetWork
FOUNDATION_EXPORT NSString* const WT_GET_SCHOOL_LESSON_ROOM;
FOUNDATION_EXPORT NSString* const WT_USE_SCHOOL_LESSON_ROOM;
FOUNDATION_EXPORT NSString* const WT_GET_SCHOOL_LESSON_CAMERA;
FOUNDATION_EXPORT NSString* const WT_GET_SCHOOL_LESSON_CAMERA_BYLESSONID;
FOUNDATION_EXPORT NSString* const WT_SET_SCHOOL_LESSON_CAMERA_STATUS;
FOUNDATION_EXPORT NSString* const WT_GET_SCHOOL_LESSON_DETAIL;
FOUNDATION_EXPORT NSString* const WT_RELEASE_SCHOOL_LESSON_ROOM;

FOUNDATION_EXPORT NSString* const WT_DEL_SCHOOL_LESSON;
FOUNDATION_EXPORT NSString* const WT_ADD_SCHOOL_LESSON;
FOUNDATION_EXPORT NSString* const WT_MODIFY_SCHOOL_LESSON;

// Setting
#pragma mark - Setting
FOUNDATION_EXPORT NSString* const WT_LATEST_VERSION;
FOUNDATION_EXPORT NSString* const WT_PUT_USER_SETTING;
FOUNDATION_EXPORT NSString* const WT_GET_USER_SETTING;


#pragma mark - Login
/** 发送短信验证码 */
FOUNDATION_EXPORT NSString* const WT_SEND_SMS;
/** 验证短信验证码 */
FOUNDATION_EXPORT NSString* const WT_CHECK_SMSCODE;
/** 发送邮箱验证码 */
FOUNDATION_EXPORT NSString* const WT_RSTRIEVE_PASSWORD_VIA_EMAIL;
/** 验证邮箱验证码 */
FOUNDATION_EXPORT NSString* const WT_RESET_PASSWORD_VIA_EMAIL;
/** 绑定手机号码 */
FOUNDATION_EXPORT NSString* const WT_USER_BIND_PHONE;
/** 手机修改密码接口 */
FOUNDATION_EXPORT NSString* const WT_RESET_PASSWORD_BY_MOBILE;
// 检查手机号码
FOUNDATION_EXPORT NSString* const WT_CHECK_MOBILE_EXIST;

@end
