//
//  ConstantsLby.h
//  omim
//
//  Created by Harry on 14-1-11.
//  Copyright (c) 2014年 OneMeter Inc. All rights reserved.
//

#ifndef yuanqutong_ConstantsLby_h
#define yuanqutong_ConstantsLby_h

#import "ConstantsYb.h"
//coordinate define

#define TABBAR_HEIGHT 50.0f

#define SCREEN_BOUNDS_WIDTH 320.0f

#define SCREEN_X_ORIGIN 5.0f

#define SCREEN_Y_ORIGIN 0.0f



//setting coordinate define


#define SETTING_TABLEVIEWCELL_WIDTH 60.0f

#define SETTING_TABLEVIEWCELL_TITLELABEL_X_ORIGIN 10.0f

#define SETTING_TABLEVIEWCELL_TITLELABEL_Y_ORIGIN 10.0f

#define SETTING_TABLEVIEWCELL_TITLELABEL_WIDTH 200.0f

#define SETTING_TABLEVIEWCELL_TITLELABEL_HEIGHT 27.0f

#define SETTING_TABLEVIEWCELL_TITLELABEL_FONT_SIZE 17.0f


#define SETTING_TABLEVIEWCELL_IMAGEVIEW_X_ORIGIN 240.0f

#define SETTING_TABLEVIEWCELL_IMAGEVIEW_Y_ORIGIN 7.0f

#define SETTING_TABLEVIEWCELL_IMAGEVIEW_WIDTH 30.0f

#define SETTING_TABLEVIEWCELL_IMAGEVIEW_HEIGHT 30.0f

#define SETTING_TABLEVIEWCELL_IMAGEVIEW_CORNERRADIUS  5.0f



#define SETTING_TABLEVIEWCELL_SUBTITLELABEL_X_ORIGIN 100.0f

#define SETTING_TABLEVIEWCELL_SUBTITLELABEL_Y_ORIGIN 10.0f

#define SETTING_TABLEVIEWCELL_SUBTITLELABEL_WIDTH 150.0f

#define SETTING_TABLEVIEWCELL_SUBTITLELABEL_HEIGHT 24.0f

#define SETTING_TABLEVIEWCELL_SUBTITLELABEL_FONT_SIZE 16.0f

//ContactInfo Define

#define PERSON_INFO_MSG_BUTTON_WIDTH  90

#define PERSON_INFO_MSG_BUTTON_HEIGHT  90

#define PERSON_INFO_X_14  14

#define PERSON_INFO_Y_14  14


#define PERSON_INFO_X_118 118

#define PERSON_INFO_NAEMLABEL_Y_POINT  10

#define PERSON_INFO_Y_10 10

//#define PERSON_INFO_WIDTH_160  160

#define PERSON_INFO_HEIGHT_20  20

#define PERSON_INFO_NAEMLABEL_FONT_SIZE 17


//UILabel *nameLabel= [[UILabel alloc] initWithFrame:CGRectMake(PERSON_INFO_SECOND_COLUMN_X_POINT, PERSON_INFO_NAEMLABEL_Y_POINT,PERSON_INFO_NAEMLABEL_WIDTH, PERSON_INFO_NAEMLABEL_HEIGHT)];


// Font Size

#define FONT_SIZE_20 20

#define FONT_SIZE_17  17

#define FONT_SIZE_15 15

#define FONT_SIZE_12  12




#define PERSON_INFO_WIDTH_50 50

#define PERSON_INFO_Y_35 35

#define PERSON_INFO_X_175 175

#define PERSON_INFO_WIDTH_130 130

#define PERSON_INFO_HEIGHT_15 15

#define PERSON_INFO_WIDTH_120 120


#define PERSON_INFO_X_216 216

#define PERSON_INFO_X_185 190

#define PERSON_INFO_X_100 90

#define PERSON_INFO_Y_74 74

#define PERSON_INFO_Y_55 55

#define PERSON_INFO_Y_44 44

#define PERSON_INFO_X_20 20

#define PERSON_INFO_Y_0 0



#define PERSON_INFO_WIDTH_160 200

#define PERSON_INFO_WIDTH_120 120

#define PERSON_INFO_WIDTH_90 90

#define PERSON_INFO_HEIGHT_37 37

#define TABLEVIEW_CELL_HEIGHT_60  60

#define TABLEVIEW_CELL_HEIGHT_120  120


#define PERSON_INFO_ADD_VALUE_16  16

#define PERSON_INFO_ADD_VALUE_68  68

#define PERSON_INFO_ADD_VALUE_136  136

#define PERSON_INFO_ADD_VALUE_204  204


#define PERSON_INFO_WIDTH_100  100

#define PERSON_INFO_WIDTH_60 70

#define PERSON_INFO_HEIGHT_60 60

#define PERSON_INFO_HEIGHT_44  44

//SearchCell

#define  SEARCH_CELL_X_5  5

#define  SEARCH_CELL_Y_5  5

#define  SEARCH_CELL_WIDTH_40  40

#define  SEARCH_CELL_HEIGHT_40  40

#define  SEARCH_CELL_X_50  50

#define  SEARCH_CELL_Y_8  8

#define  SEARCH_CELL_WIDTH_250  250

#define  SEARCH_CELL_HEIGHT_17  17

#define  SEARCH_CELL_Y_31  31

#define  SEARCH_CELL_WIDTH_40  40

#define  SEARCH_CELL_HEIGHT_12  12

#define  SEARCH_CELL_X_95  95

#define  SEARCH_CELL_Y_31  31

#define  SEARCH_CELL_WIDTH_210  210





#endif
